'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Person
    
    '''<summary>
    '''lblnew_person control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblnew_person As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbldiv_person control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldiv_person As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbldiv_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldiv_type As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''person_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents person_name As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlrealtion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlrealtion As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Text1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Text1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''Text2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Text2 As Global.System.Web.UI.HtmlControls.HtmlInputText
End Class
