'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PhotosUpload
    
    '''<summary>
    '''pnlImagesUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlImagesUpload As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''mduImages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mduImages As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''pnlImages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlImages As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''upImagesUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upImagesUpload As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lbImagesClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbImagesClose As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''AjaxPhotoUploadImages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AjaxPhotoUploadImages As Global.AjaxControlToolkit.AjaxFileUpload
    
    '''<summary>
    '''cmdImagesok control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdImagesok As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''divUploadedImages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divUploadedImages As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
